server:
  port: 8083

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/order_db?sslMode=DISABLED
    username: root
    password: meomeo123

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.r2dbc.mysql: DEBUG
    org.springframework.data.r2dbc: DEBUG
